// react/src/components/InstallList/index.tsx
import React from "react";
import { useRecoilValue } from "recoil";
import { installListState } from "~/stores/software";
import SoftwareComponent from "../Software";
import style from "./style.module.scss";

const InstallList: React.FC = () => {
  const installList = useRecoilValue(installListState);

  if (installList.length > 0) {
    return (
      <>
        <h2 className={style.title}>已安装</h2>

        {installList.map((item) => (
          <SoftwareComponent software={item} key={item.id} />
        ))}
      </>
    );
  }

  return <></>;
};

export default InstallList;

// vue/src/components/InstallList.vue
<script lang="ts" setup>
  import { useInstallList } from "@/stores/software";
  import { storeToRefs } from "pinia";

  import SoftwareComponent from "./Software.vue";

  const installListStore = useInstallList();
  const { installList } = storeToRefs(installListStore);
</script>

<template>
  <div v-if="installList.length > 0" class="container">
    <h2 class="title">已安装</h2>

    <template v-for="item in installList" :key="item.id">
      <SoftwareComponent :software="item" />
    </template>
  </div>
</template>

<style lang="scss" scoped>
  .container {
    padding-block: var(--padding-block);
  }

  .title {
    font-weight: 500;
    font-size: 13px;
    height: 28px;
    line-height: 28px;
    color: var(--text-gray);
    padding-inline: var(--padding-inline);
  }
</style>
