// src/components/InstallList.tsx
import React, { useMemo } from 'react'
import { useRecoilValue } from 'recoil'
import { installMapState, InstallStatus } from '../stores/install-store'
import { sourceData, Tool } from '../assets/data'
import style from '../assets/styles/component/InstallList.module.css'
import ToolItem from './ToolItem'

export type InstallTool = Tool & {
  version: string
  key: string
  status: InstallStatus
}

const InstallList: React.FC = () => {
  const installMap = useRecoilValue(installMapState)

  const list = useMemo(() => {
    let toolList: InstallTool[] = []
    let allToolMap = new Map<string, Tool>()

    sourceData.forEach(item => allToolMap.set(item.name, item))

    for (const [key, value] of installMap) {
      const temp: InstallTool = {
        ...allToolMap.get(key.name)!,
        key: key.name + key.version,
        version: key.version,
        status: value.status,
      }
      toolList.push(temp)
    }

    return toolList
  }, [installMap])

  if (list.length > 0) {
    return (
      <>
        <h2 className={style.title}>已安装</h2>

        {list.map(item => (
          <ToolItem tool={item} key={item.key} />
        ))}
      </>
    )
  }

  return <></>
}

export default InstallList

// vue/src/components/InstallList.vue
<script lang="ts" setup>
  import { sourceData, type Software } from "@/assets/data";
  import { useInstallMap, type InstallSoftware } from "@/stores/software";
  import { storeToRefs } from "pinia";
  import { computed } from "vue";

  import SoftwareComponent from "./Software.vue";

  const installMapStore = useInstallMap();
  const { installMap } = storeToRefs(installMapStore);

  const installList = computed(() => {
    let list: InstallSoftware[] = [];

    let allSoftwareMap = new Map<string, Software>();
    sourceData.forEach((item) => allSoftwareMap.set(item.name, item));

    for (const [key, value] of installMap.value) {
      const temp: InstallSoftware = {
        ...allSoftwareMap.get(key.name)!,
        key: key.name + key.version,
        version: key.version,
        status: value.status,
      };
      list.push(temp);
    }
    return list;
  });
</script>

<template>
  <h2 class="title" v-if="installList.length > 0">已安装</h2>

  <template v-for="item in installList" :key="item.version + item.key">
    <SoftwareComponent :software="item" />
  </template>
</template>

<style lang="scss" scoped>
  .title {
    font-size: 13px;
    color: var(--text-gray);
    cursor: pointer;
  }
</style>
