// vue/src/components/Core.vue
<script lang="ts" setup>
  import { emitterKey } from "@/emitter";
  import { useProgress } from "@/stores/progress";
  import { useInstallMap, type InstallMapKey } from "@/stores/software";
  import { inject, watch } from "vue";

  const emitter = inject(emitterKey);

  type InstallE = {
    name: string;
    version: string;
  };

  const installMapstore = useInstallMap();
  const progressStore = useProgress();

  const handleInstall = (e: unknown) => {
    const arg: InstallMapKey = {
      name: (e as InstallE).name,
      version: (e as InstallE).version,
    };

    installMapstore.installMap.set(arg, { status: "downloading" });
    const progressKey = `${arg.name}${arg.version}`;

    let percent = progressStore.progressMap.get(progressKey);
    if (percent === undefined) {
      percent = 0;
      progressStore.progressMap.set(progressKey, percent);
    }

    let intervalID = setInterval(() => {
      if (percent! < 100) {
        percent =
          percent! + Math.random() * 10 > 100
            ? 100
            : (percent = percent! + Math.random() * 10);
      } else {
        clearInterval(intervalID);

        // 修改状态为 installing
        installMapstore.installMap.set(arg, { status: "installing" });

        // 2000ms 后修改为 installed
        setTimeout(() => {
          installMapstore.installMap.set(arg, { status: "installed" });
        }, 2000);
      }

      progressStore.progressMap.set(progressKey, percent!);
    }, 1000);
  };

  emitter?.on("install", handleInstall);
</script>

<template></template>

// src/components/Core.tsx
import { useEffect } from 'react'
import { useRecoilState, useSetRecoilState } from 'recoil'
import { subscribe, unsubscribe } from '../events'
import { InstallMapKey, installMapState } from '../stores/install-store'
import { progressState } from '../stores/progress-store'

const Core = () => {
  const setInstallMap = useSetRecoilState(installMapState)
  const [progress, setProgress] = useRecoilState(progressState)

  const handleInstall = (data: any) => {
    if (data.detail && data.detail.name && data.detail.version) {
      const arg: InstallMapKey = {
        name: data.detail.name,
        version: data.detail.version,
      }

      setInstallMap(prev => new Map(prev.set(arg, { status: 'downloading' })))

      const progressKey = `${arg.name}${arg.version}`

      let percent = progress.get(progressKey)

      if (percent === undefined) {
        percent = 0
        setProgress(prev => new Map(prev.set(progressKey, 0)))
      }

      let intervalId = setInterval(() => {
        if (percent! < 100) {
          percent =
            percent! + Math.random() * 10 > 100
              ? 100
              : (percent = percent! + Math.random() * 10)
        } else {
          clearInterval(intervalId)
          setInstallMap(
            prev => new Map(prev.set(arg, { status: 'installing' }))
          )

          setTimeout(() => {
            setInstallMap(
              prev => new Map(prev.set(arg, { status: 'installed' }))
            )
          }, 2000)
        }
        setProgress(prev => new Map(prev.set(progressKey, percent!)))
      }, 1000)
    }
  }

  useEffect(() => {
    subscribe('onInstall', handleInstall)

    return () => {
      unsubscribe('onInstall', handleInstall)
    }
  }, [])

  return <></>
}

export default Core
